import os, time, socket, subprocess, requests
from google import genai
from google.genai import types

class AIManager:

    def __init__(self, api_key, audio_service):
        self.audio_service = audio_service
        self.ollama_process = None  
        if api_key:
            try:
                self.gemini_client = genai.Client(api_key=api_key)
            except Exception as e:
                print(f"Aviso: No se pudo iniciar el cliente Gemini: {e}")
                self.gemini_client = None
        else:
            print("Aviso: No se proporcionó API Key. Se usará IA local por defecto.")
            self.gemini_client = None

    def _internet(self):
        """Metodo para comprobar la conexion a internet"""
        """Method to check internet connection"""
        try:
            socket.create_connection(("8.8.8.8", 53), timeout=1.0)
            self.shutdown_ollama()
            return True
        except OSError:
            return False

    def _start_ollama(self):
        """Metodo para encender la IA local"""
        """Method to initiate the local AI"""
        try:
            requests.get("http://localhost:11434/", timeout=1)
        except requests.ConnectionError:
            flags = subprocess.CREATE_NO_WINDOW if os.name == 'nt' else 0
            
            self.ollama_process = subprocess.Popen(
                ["ollama", "serve"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                creationflags=flags
            )
            time.sleep(2.5)

    def shutdown_ollama(self):
        """Metodo para apagar la IA local"""
        """Method to shutdown the local AI"""
        try:
            if os.name == 'nt':  # Windows
                subprocess.run(
                    ["taskkill", "/F", "/IM", "llama-server.exe"],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
                )
            else:  # Linux/Mac
                subprocess.run(["pkill", "-f", "ollama"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                subprocess.run(["pkill", "-f", "llama-server"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            
            if self.ollama_process:
                self.ollama_process.wait(timeout=2)
                
        except Exception as e:
            print(f"Aviso al cerrar Ollama: {e}")
        finally:
            self.ollama_process = None

    def _clean_code(self, raw_code):
        """Metodo para eliminar la parte estatica del codigo generada por el propio programa"""
        """Method to delete the static part of the code generated by the program"""
        if not raw_code.strip():
            return ""

        lines = raw_code.split('\n')
        
        read = False
        visible_lines = []
        for line in enumerate(lines):
            if read:
                visible_lines.append(line[1])
            if line[1] == "# --- Programa Principal ---":
                read = True
            
        return "\n".join(visible_lines)

    def explain_code(self, code_dir, callback_state):
        """
            Metodo en cascada para explicar el codigo
            1. Explica el codigo con Gemini
            2. Si no puede lo explica la IA local
            3. Si falla lee el codigo literalmente
        """
        """
            Method on cascade to explain the code
            1. Explain the code with gemini
            2. If not possible the local AI explains it
            3. If it fails reads the code literally
        """
        try:
            with open(code_dir, "r", encoding="utf-8") as file:
                code = file.read()
        except FileNotFoundError:
            self.audio_service.read_text("Aún no se ha generado ningún programa.")
            return

        clean_code = self._clean_code(code)
        
        if not clean_code.strip():
            self.audio_service.read_text("El archivo de código está vacío.")
            return

        prompt = f"""Eres un asistente de accesibilidad. Explica en una o dos frases, con lenguaje cotidiano
        y sin usar términos técnicos de programación, puedes especificar que acciones se pueden hacer y
        "cuales son los resultados, qué hace este programa físico:\n\n{clean_code}"""

        internet = not self._internet()

        if not internet and self.gemini_client is not None:
            callback_state("Estado: Conectando con Gemini...", "#8E44AD")
            self.audio_service.read_text("Conectando con Gemini para la explicación de código")
            time.sleep(3)
            try:
                config = types.GenerateContentConfig(max_output_tokens=80, temperature=0.2)
                answer = self.gemini_client.models.generate_content(
                    model='gemini-flash-lite-latest',
                    contents=prompt,
                    config=config
                )
                callback_state("Estado: Explicación rápida por Gemini", "#2FA572")
                self.audio_service.read_text(answer.text.strip())
                return 
            except Exception as e_gemini:
                print(f"Fallo en Gemini: {e_gemini}")
                callback_state("Estado: Fallo API Gemini. Iniciando IA local...", "#D4AC0D")
        else:
            if self.gemini_client is None:
                callback_state("Estado: Sin API Key. Iniciando IA local...", "#D4AC0D")
            else:
                callback_state("Estado: Sin internet. Iniciando IA local...", "#D4AC0D")
        try:
            self.audio_service.read_text("Usando IA local, puede tardar en responder")
            self._start_ollama()
            
            system_instructions = (
                "Eres un asistente que explica programas de Micro:bit a personas sin conocimientos técnicos. "
                "Responde SIEMPRE con una sola frase corta. "
                "Menciona siempre la causa física (ej: pulsar botón A, agitar, radio) y el efecto (ej: mostrar corazón, sonido). "
                "Prohibido usar términos de programación y prohibido escribir código."
            )

            local_answer = requests.post(
                "http://localhost:11434/api/generate", 
                json={
                    "model": "phi3", 
                    "system": system_instructions, 
                    "prompt": clean_code,
                    "stream": False,
                    "options": {
                        "temperature": 0.1,
                        "num_predict": 80
                    }
                }, 
                timeout=30
            )
            local_answer.raise_for_status()
            
            explanation = local_answer.json().get("response", "").strip()
            
            if "```" in explanation:
                explanation = explanation.split("```")[0].strip()
                
            callback_state("Estado: Explicación por IA Local", "#2FA572")
            self.audio_service.read_text(explanation, internet)
            return 
            
        except Exception as e_ollama:
            print(f"Fallo en Ollama local: {e_ollama}")

        self.shutdown_ollama()
        callback_state("Estado: IAs no disponibles. Leyendo literalmente.", "#E67E22")
        self.audio_service.read_text("IAs no disponibles. Modo sin conexión. ")
        self.audio_service.read_literal_code(code_dir)