from utils.strings import t


def strip_static_header(code):
    """Elimina la parte estatica del codigo generada por el propio programa, dejando solo lo que hay a partir del marcador de programa principal"""
    """Removes the static part of the code generated by the program itself, leaving only what's after the main-program marker"""
    if not code:
        return ""

    lines = code.split('\n')
    read = False
    visible_lines = []
    for line in lines:
        if read:
            visible_lines.append(line)
        if line == t("marker_main_program"):
            read = True

    return "\n".join(visible_lines)


def strip_tts_wrapper_lines(code):
    """Quita las lineas print('TTS:' + str(...)) / speech.say(str(...)) que el compilador inserta automaticamente delante de cada display.show/scroll cuando el modo de voz esta activo. Son un mecanismo interno de accesibilidad, no algo que el estudiante haya colocado con un bloque - si se le mandan a una IA para que explique el programa, las trata como codigo real y el resultado sale confuso"""
    """Removes the print('TTS:' + str(...)) / speech.say(str(...)) lines the compiler automatically inserts before every display.show/scroll when voice mode is active. They're an internal accessibility mechanism, not something the student placed with a block - if sent to an AI to explain the program, it treats them as real code and the result comes out confusing"""
    if not code:
        return code

    kept_lines = []
    for line in code.split('\n'):
        stripped = line.strip()
        if stripped.startswith("print('TTS:'") or stripped.startswith("speech.say(str("):
            continue
        kept_lines.append(line)

    return "\n".join(kept_lines)