from utils.language import get_language

STRINGS = {
    "es": {
        # --- Ventana principal / navegación ---
        "window_title": "ONCE: MicroPython por bloques",
        "tab_camera": "Cámara y Control",
        "tab_qrs": "Generador de QRs",
        "tab_json": "Editor de Diccionario",
        "btn_contrast_mode": "Modo Contraste",
        "btn_change_language": "Idioma",
        "btn_standard_mode": "Modo Estándar",
        "focus_high_contrast_on": "Modo de alto contraste activado.",
        "focus_standard_on": "Modo estándar activado.",
        "status_ui_frozen": "Estado: Interfaz bloqueada (Esperando respuesta por voz...)",
        "status_camera_active": "Estado: Cámara Activa",
        "focus_rotate_camera": "Rotar cámara",
        "focus_shutdown_camera": "Apagar cámara",
        "sys_ready": "Sistema listo. La cámara está en modo horizontal.",

        # --- Atajos de teclado (etiqueta leída al primer toque) ---
        "shortcut_capture": "Tomar foto",
        "shortcut_send": "Enviar a MicroBit",
        "shortcut_explain": "Explicar con IA",
        "shortcut_read": "Leer QRs Mesa",
        "shortcut_tts": "Modo de lectura por variable",
        "shortcut_review": "Modificar variables",

        # --- Pestaña Cámara ---
        "btn_capture": "Tomar Foto",
        "btn_send": "Enviar a MicroBit",
        "btn_explain": "Explicar con IA",
        "btn_read": "Leer QRs",
        "btn_review": "Modificar Variables",
        "tts_mode_pc": "Voz: PC",
        "tts_mode_board": "Voz: Placa",
        "tts_mode_off": "Voz: Apagada",
        "camera_main": "Cámara Principal",
        "camera_secondary": "Cámara Secundaria ({idx})",
        "status_edit_mode": "Estado: MODO EDICIÓN ACTIVO",
        "status_save_error": "Error al guardar: {error}",
        "status_quick_save": "Estado: Guardado rápido completado",
        "status_camera_off": "Estado: Cámara Apagada",
        "code_not_generated": "# Archivo no generado de momento.",
        "status_waiting_capture": "Estado: Esperando captura...",
        "status_no_syntax_errors": "Estado: Código sin errores",
        "status_syntax_error": "Error de Sintaxis en línea {lineno}",
        "error_syntax_audio": "Atención. Hay un error de sintaxis en el archivo.",
        "upload_success": "Código subido con éxito",
        "upload_error_missing_module": "Error. No se encuentra el módulo uflash. Instálalo con 'pip install uflash'.",
        "upload_error_no_board": "Atención. No se detecta la placa Micro bit conectada. Revisa el cable USB.",
        "upload_error_no_python": "Error. No se encuentra Python en el sistema.",

        # --- Pestaña Diccionario (JSON) ---
        "title_add_block": "Añadir Nuevo Bloque",
        "lbl_qr_text": "Texto del QR:",
        "placeholder_qr_text": "ej: encender leds",
        "lbl_python_code": "Código Python:",
        "placeholder_python_code": "ej: display.show",
        "lbl_node_type": "Tipo de Nodo:",
        "lbl_arguments": "Argumentos:",
        "btn_save_block": "Guardar Bloque",
        "btn_update_block": "Actualizar Bloque",
        "btn_cancel_edit": "Cancelar Edición",
        "title_blocks_in_memory": "Bloques Actuales en Memoria",
        "lbl_search": "Buscar:",
        "placeholder_search_blocks": "Escribe para filtrar bloques...",
        "table_header_block_translation": "Bloque -> Traducción",
        "table_header_edit": "Editar",
        "table_header_delete": "Borrar",
        "table_header_sel": "Sel",
        "error_name_code_required": "Error: El nombre y el código son obligatorios.",
        "block_saved_success": "¡Bloque '{name}' guardado con éxito!",
        "error_saving": "Error al guardar: {error}",
        "block_deleted": "Bloque '{name}' eliminado.",
        "error_deleting": "Error al eliminar: {error}",
        "blocks_deleted_success": "Se han eliminado {count} bloques seleccionados.",
        "blocks_deleted_partial": "Eliminados {count}. Fallaron: {failures}.",
        "blocks_deleted_none": "No se ha podido eliminar ninguno. Fallaron: {failures}.",
        "title_editing": "Editando: {name}",

        # --- Pestaña QRs ---
        "title_qr_print": "Mesa de Impresión de Códigos QR",
        "btn_show_active": "Mostrar > 0",
        "btn_show_all": "Mostrar Todos",
        "btn_all_one": "Todos a 1",
        "btn_clear_zero": "Limpiar a 0",
        "lbl_search_block": "Buscar bloque:",
        "placeholder_search": "Escribe para filtrar...",
        "table_header_block_name": "Nombre del Bloque",
        "table_header_quantity": "Cantidad",
        "lbl_size_cm": "Tamaño (cm):",
        "btn_generate_pdf": "Generar PDF de Impresión",
        "error_invalid_size": "Error: Tamaño inválido. Usa formato '5.0'",
        "error_no_quantity": "No has seleccionado ninguna cantidad.",
        "dialog_save_pdf_title": "Guardar PDF de Códigos QR",
        "dialog_pdf_default_name": "qrs_impresion.pdf",
        "dialog_pdf_filter": "Archivos PDF (*.pdf)",
        "save_cancelled": "Operación de guardado cancelada.",
        "generating_pdf": "Generando imágenes y PDF...",
        "pdf_success": "¡Éxito! PDF guardado en: {path}",
        "pdf_error": "Error al generar PDF: {error}",
        "list_updated": "Lista actualizada desde memoria.",

        # --- Voz del programa (ProgramBuilder) ---
        "warn_load_state_failed": "Aviso: no se ha podido cargar el estado guardado del programa anterior.",
        "warn_save_state_failed": "Atención. No se ha podido guardar el estado del programa.",
        "need_capture_first": "Primero debes capturar un programa para poder modificar sus variables.",
        "starting_var_review": "Iniciando el modo de repaso de variables.",
        "vars_modified": "Variables modificadas. El código nuevo ya está generado.",
        "camera_not_active": "La cámara no está activa.",
        "no_blocks_detected": "No detecto ningún bloque en la pantalla.",
        "code_reading_intro": "El programa actual es el siguiente... {code}",
        "no_blocks_on_table": "No detecto ningún bloque en la mesa.",
        "qr_position_item": "posición {index}, {block}",
        "qrs_detected_reading": "Detectados {count} bloques. Leyendo de arriba a abajo... {list}.",
        "qr_count_singular": "{count} bloque detectado.",
        "qr_count_plural": "{count} bloques detectados.",
        "uploading_to_board": "Subiendo el programa a la placa Micro:bit.",
        "no_program_generated": "Aún no se ha generado ningún programa.",
        "tts_mode_pc_on": "Modo de voz por ordenador activado.",
        "tts_mode_board_on": "Modo de voz en la placa activado.",
        "tts_mode_off_on": "Voz de ejecución desactivada.",
        "capturing": "Capturando.",
        "ask_modify_value": "{intro}El valor actual es {value}. ¿Quieres modificarlo?",
        "ask_modify_name": "{intro}El nombre actual es {value}. ¿Quieres modificarlo?",
        "ask_new_value": "Dime el nuevo valor",
        "ask_new_name": "Dime el nuevo nombre",
        "ask_value": "{intro}Dime el valor",
        "ask_var_name": "{intro}Dime el nombre de la variable",
        "ask_use_last_var": "{intro}¿Quieres usar la última variable declarada, llamada {name}?",
        "ask_use_other_var": "¿Quieres usar otra de las variables anteriores?",
        "ask_search_var_name": "Dime el nombre de la variable para buscarla.",
        "please_speak_name": "Por favor, dime el nombre hablando.",
        "var_not_found": "No he encontrado esa variable. Volvamos a intentarlo.",
        "ask_name": "{intro}Dime el nombre",
        "ask_expand_program": "El bloque {names} toca el borde {dir}. ¿Quieres ampliar el programa haciendo otra foto?",
        "ok_expand_photo": "De acuerdo. Pon el bloque {names} en la nueva foto para usarlo de referencia. Pulsa capturar cuando estés listo.",
        "ok_cancel_expand": "De acuerdo, cancelando el resto de ampliaciones y procesando el programa.",
        "code_generated": "El código nuevo ya está generado.",
        "dir_side": "lateral",
        "dir_bottom": "inferior",
        "marker_init_sound": "# --- Sonido de inicialización ---",
        "marker_main_program": "# --- Programa Principal ---",
        "generic_number_key": "numero",
        "generic_true_key": "verdadero",
        "generic_false_key": "falso",
        "generic_declare_var_key": "declarar variable",
        "generic_reference_var_key": "variable",
        "generic_assign_val_key": "valor variable",
        "overlay_num_prefix": "Num: ",

        # --- Explicación por IA ---
        "code_empty": "El archivo de código está vacío.",
        "status_connecting_gemini": "Estado: Conectando con Gemini...",
        "connecting_gemini_audio": "Conectando con Gemini para la explicación de código",
        "status_gemini_explained": "Estado: Explicación rápida por Gemini",
        "status_gemini_failed": "Estado: Fallo API Gemini. Iniciando IA local...",
        "status_no_api_key": "Estado: Sin API Key. Iniciando IA local...",
        "status_no_internet": "Estado: Sin internet. Iniciando IA local...",
        "using_local_ai": "Usando IA local, puede tardar en responder",
        "status_local_explained": "Estado: Explicación por IA Local",
        "status_ai_unavailable": "Estado: IAs no disponibles. Leyendo literalmente.",
        "ai_unavailable_audio": "IAs no disponibles. Modo sin conexión. ",
        "gemini_prompt": (
            "Eres un asistente de accesibilidad. Explica en una o dos frases, con lenguaje "
            "cotidiano y sin usar términos técnicos de programación, qué acciones se pueden "
            "hacer y cuáles son los resultados, qué hace este programa físico:\n\n{code}"
        ),
        "ollama_system_instructions": (
            "Eres un asistente que explica programas de Micro:bit a personas sin conocimientos técnicos. "
            "Responde con una frase corta; si el programa tiene más de un comportamiento independiente, usa como mucho dos frases cortas, una por comportamiento. "
            "Menciona siempre la causa física (ej: pulsar botón A, agitar, radio) y el efecto (ej: mostrar corazón, sonido). "
            "Si ves líneas como print('TTS:' ...) o speech.say(...), ignóralas por completo: son un mecanismo interno para leer resultados en voz alta, no algo que expliques ni menciones. "
            "Prohibido usar términos de programación y prohibido escribir código."
        ),

        # --- Control por voz ---
        "voice_ready": "El control por voz está listo.",
        "processing": "Procesando.",
        "command_not_recognized": "Comando no reconocido.",
        "skip_using_default": "Saltando paso. Usando valor por defecto.",
        "tap_not_allowed_speak": "Por favor, dígame la respuesta hablando, no uses los toques rápidos.",
        "understood_confirm": "He entendido {text}. ¿Es correcto?",
        "skipping_validation": "Omitiendo validación.",
        "lets_repeat": "De acuerdo, vamos a repetirlo.",

        # Palabras clave reconocidas por voz (deben ir en minúsculas)
        "kw_capture": ["foto", "capturar", "cámara"],
        "kw_send": ["enviar", "subir", "placa", "microbit"],
        "kw_explain": ["explicar", "inteligencia", "ia"],
        "kw_explain_phrase": "qué hace",
        "kw_read": ["leer", "mesa", "qr"],
        "kw_tts": ["voz", "audio", "hablar", "sonido"],
        "kw_review": ["repasar", "modificar", "variables"],
        "kw_yes": ["sí", "si", "correcto"],
        "kw_skip": ["pasar", "omitir"],
        "kw_casual_yes": ["claro"],
        "list_join_and": ", y ",

        # --- translator.py: errores y contextos hablados durante la generación ---
        "err_expected_right": "# ERROR: El bloque '{block}' esperaba {expect} a su derecha.",
        "err_missing_after": "\n# ERROR: Después de '{block}', faltaba {expect}.",
        "err_unknown_block": "# ERROR: El bloque '{block}' es desconocido o no está en el diccionario.",
        "err_loose_block": "# ERROR: El bloque '{block}' está suelto.",
        "context_declare_var": "declarar una variable nueva",
        "context_value_for": "el valor para {name}",
        "context_general_order": "una orden general",
        "context_control_method_subject": "un sujeto o sensor",
        "context_control_method_of": "el método de control de {block}",
        "context_control_function_arg": "un argumento o condición",
        "context_function_of": "la función {block}",
        "context_method_subject_needed": "un sujeto para aplicarse",
        "context_subject_of": "el sujeto de {block}",
        "context_arg_number": "el argumento número {n}",
        "context_arg_of": "el argumento de {block}",
        "context_condition_of": "la condición de {block}",
        "context_block_next_to": "el bloque junto a {block}",
        "context_another_condition": "otra condición",
        "context_arg_n_short": "argumento {n}",
        "context_arg_of_short": "argumento de {block}",

        # --- translator.py: números hablados ---
        "number_words": {
            "cero": "0", "uno": "1", "dos": "2", "tres": "3", "cuatro": "4",
            "cinco": "5", "seis": "6", "siete": "7", "ocho": "8", "nueve": "9",
            "diez": "10", "once": "11", "doce": "12", "trece": "13", "catorce": "14",
            "quince": "15", "dieciséis": "16", "diecisiete": "17", "dieciocho": "18",
            "diecinueve": "19", "veinte": "20", "treinta": "30", "cuarenta": "40",
            "cincuenta": "50", "sesenta": "60", "setenta": "70", "ochenta": "80",
            "noventa": "90", "cien": "100",
        },
        "number_prefix": ["número ", "numero "],
        "decimal_connectors": [" coma ", " con "],
        "junction_word": " y ",
        "image_word": "imagen",
        # Notas musicales para "reproducir melodía": solfeo y notación
        # anglosajona indistintamente, siempre traducidas a la notación
        # anglosajona que espera music.play() en MicroPython.
        "note_names": {
            "do": "c", "re": "d", "mi": "e", "fa": "f", "sol": "g", "la": "a", "si": "b",
            "c": "c", "d": "d", "e": "e", "f": "f", "g": "g", "a": "a", "b": "b",
        },
    },

    "en": {
        # --- Main window / navigation ---
        "window_title": "ONCE: MicroPython by Blocks",
        "tab_camera": "Camera & Control",
        "tab_qrs": "QR Generator",
        "tab_json": "Dictionary Editor",
        "btn_contrast_mode": "Contrast Mode",
        "btn_change_language": "Language",
        "btn_standard_mode": "Standard Mode",
        "focus_high_contrast_on": "High contrast mode enabled.",
        "focus_standard_on": "Standard mode enabled.",
        "status_ui_frozen": "Status: Interface locked (Waiting for voice response...)",
        "status_camera_active": "Status: Camera Active",
        "focus_rotate_camera": "Rotate camera",
        "focus_shutdown_camera": "Turn off camera",
        "sys_ready": "System ready. The camera is in horizontal mode.",

        # --- Keyboard shortcuts (label read on first tap) ---
        "shortcut_capture": "Take photo",
        "shortcut_send": "Send to MicroBit",
        "shortcut_explain": "Explain with AI",
        "shortcut_read": "Read table QRs",
        "shortcut_tts": "Variable reading mode",
        "shortcut_review": "Modify variables",

        # --- Camera tab ---
        "btn_capture": "Take Photo",
        "btn_send": "Send to MicroBit",
        "btn_explain": "Explain with AI",
        "btn_read": "Read QRs",
        "btn_review": "Modify Variables",
        "tts_mode_pc": "Voice: PC",
        "tts_mode_board": "Voice: Board",
        "tts_mode_off": "Voice: Off",
        "camera_main": "Main Camera",
        "camera_secondary": "Secondary Camera ({idx})",
        "status_edit_mode": "Status: EDIT MODE ACTIVE",
        "status_save_error": "Error saving: {error}",
        "status_quick_save": "Status: Quick save completed",
        "status_camera_off": "Status: Camera Off",
        "code_not_generated": "# No file generated yet.",
        "status_waiting_capture": "Status: Waiting for capture...",
        "status_no_syntax_errors": "Status: No errors in code",
        "status_syntax_error": "Syntax error on line {lineno}",
        "error_syntax_audio": "Attention. There is a syntax error in the file.",
        "upload_success": "Code uploaded successfully",
        "upload_error_missing_module": "Error. The uflash module was not found. Install it with 'pip install uflash'.",
        "upload_error_no_board": "Attention. No Micro:bit board detected. Check the USB cable.",
        "upload_error_no_python": "Error. Python was not found on this system.",

        # --- Dictionary (JSON) tab ---
        "title_add_block": "Add New Block",
        "lbl_qr_text": "QR Text:",
        "placeholder_qr_text": "e.g. turn on leds",
        "lbl_python_code": "Python Code:",
        "placeholder_python_code": "e.g. display.show",
        "lbl_node_type": "Node Type:",
        "lbl_arguments": "Arguments:",
        "btn_save_block": "Save Block",
        "btn_update_block": "Update Block",
        "btn_cancel_edit": "Cancel Edit",
        "title_blocks_in_memory": "Current Blocks in Memory",
        "lbl_search": "Search:",
        "placeholder_search_blocks": "Type to filter blocks...",
        "table_header_block_translation": "Block -> Translation",
        "table_header_edit": "Edit",
        "table_header_delete": "Delete",
        "table_header_sel": "Sel",
        "error_name_code_required": "Error: Name and code are required.",
        "block_saved_success": "Block '{name}' saved successfully!",
        "error_saving": "Error saving: {error}",
        "block_deleted": "Block '{name}' deleted.",
        "error_deleting": "Error deleting: {error}",
        "blocks_deleted_success": "{count} selected blocks deleted.",
        "blocks_deleted_partial": "Deleted {count}. Failed: {failures}.",
        "blocks_deleted_none": "Couldn't delete any of them. Failed: {failures}.",
        "title_editing": "Editing: {name}",

        # --- QRs tab ---
        "title_qr_print": "QR Code Printing Table",
        "btn_show_active": "Show > 0",
        "btn_show_all": "Show All",
        "btn_all_one": "All to 1",
        "btn_clear_zero": "Clear to 0",
        "lbl_search_block": "Search block:",
        "placeholder_search": "Type to filter...",
        "table_header_block_name": "Block Name",
        "table_header_quantity": "Quantity",
        "lbl_size_cm": "Size (cm):",
        "btn_generate_pdf": "Generate Print PDF",
        "error_invalid_size": "Error: Invalid size. Use format '5.0'",
        "error_no_quantity": "You haven't selected any quantity.",
        "dialog_save_pdf_title": "Save QR Codes PDF",
        "dialog_pdf_default_name": "qrs_print.pdf",
        "dialog_pdf_filter": "PDF Files (*.pdf)",
        "save_cancelled": "Save operation cancelled.",
        "generating_pdf": "Generating images and PDF...",
        "pdf_success": "Success! PDF saved at: {path}",
        "pdf_error": "Error generating PDF: {error}",
        "list_updated": "List updated from memory.",

        # --- Program voice (ProgramBuilder) ---
        "warn_load_state_failed": "Notice: the saved state of the previous program couldn't be loaded.",
        "warn_save_state_failed": "Attention. The program state couldn't be saved.",
        "need_capture_first": "You need to capture a program first before you can modify its variables.",
        "starting_var_review": "Starting variable review mode.",
        "vars_modified": "Variables modified. The new code has been generated.",
        "camera_not_active": "The camera is not active.",
        "no_blocks_detected": "I don't detect any blocks on the screen.",
        "code_reading_intro": "The current program is the following... {code}",
        "no_blocks_on_table": "I don't detect any blocks on the table.",
        "qr_position_item": "position {index}, {block}",
        "qrs_detected_reading": "Detected {count} blocks. Reading from top to bottom... {list}.",
        "qr_count_singular": "{count} block detected.",
        "qr_count_plural": "{count} blocks detected.",
        "uploading_to_board": "Uploading the program to the Micro:bit board.",
        "no_program_generated": "No program has been generated yet.",
        "tts_mode_pc_on": "Computer voice mode enabled.",
        "tts_mode_board_on": "Board voice mode enabled.",
        "tts_mode_off_on": "Execution voice disabled.",
        "capturing": "Capturing.",
        "ask_modify_value": "{intro}The current value is {value}. Do you want to change it?",
        "ask_modify_name": "{intro}The current name is {value}. Do you want to change it?",
        "ask_new_value": "Tell me the new value",
        "ask_new_name": "Tell me the new name",
        "ask_value": "{intro}Tell me the value",
        "ask_var_name": "{intro}Tell me the variable's name",
        "ask_use_last_var": "{intro}Do you want to use the last declared variable, called {name}?",
        "ask_use_other_var": "Do you want to use another one of the previous variables?",
        "ask_search_var_name": "Tell me the variable's name to search for it.",
        "please_speak_name": "Please say the name out loud.",
        "var_not_found": "I couldn't find that variable. Let's try again.",
        "ask_name": "{intro}Tell me the name",
        "ask_expand_program": "The block {names} touches the {dir} edge. Do you want to expand the program by taking another photo?",
        "ok_expand_photo": "Alright. Put the {names} block in the new photo to use it as a reference. Press capture when you're ready.",
        "ok_cancel_expand": "Alright, cancelling the rest of the expansions and processing the program.",
        "code_generated": "The new code has been generated.",
        "dir_side": "side",
        "dir_bottom": "bottom",
        "marker_init_sound": "# --- Initialization Sound ---",
        "marker_main_program": "# --- Main Program ---",
        "generic_number_key": "number",
        "generic_true_key": "true",
        "generic_false_key": "false",
        "generic_declare_var_key": "declare variable",
        "generic_reference_var_key": "variable",
        "generic_assign_val_key": "assign value",
        "overlay_num_prefix": "Num: ",

        # --- AI explanation ---
        "code_empty": "The code file is empty.",
        "status_connecting_gemini": "Status: Connecting to Gemini...",
        "connecting_gemini_audio": "Connecting to Gemini for the code explanation",
        "status_gemini_explained": "Status: Quick explanation by Gemini",
        "status_gemini_failed": "Status: Gemini API failed. Starting local AI...",
        "status_no_api_key": "Status: No API Key. Starting local AI...",
        "status_no_internet": "Status: No internet. Starting local AI...",
        "using_local_ai": "Using local AI, it may take a while to respond",
        "status_local_explained": "Status: Explanation by Local AI",
        "status_ai_unavailable": "Status: AIs unavailable. Reading literally.",
        "ai_unavailable_audio": "AIs unavailable. Offline mode. ",
        "gemini_prompt": (
            "You are an accessibility assistant. In one or two sentences, using everyday "
            "language and no programming jargon, explain what actions this physical program "
            "can perform and what the results are:\n\n{code}"
        ),
        "ollama_system_instructions": (
            "You are an assistant that explains Micro:bit programs to people with no technical background. "
            "Respond with one short sentence; if the program has more than one independent behavior, use at most two short sentences, one per behavior. "
            "Always mention the physical cause (e.g. pressing button A, shaking, radio) and the effect (e.g. showing a heart, sound). "
            "If you see lines like print('TTS:' ...) or speech.say(...), ignore them completely: they're an internal mechanism for reading results aloud, not something to explain or mention. "
            "Programming terms are forbidden, and writing code is forbidden."
        ),

        # --- Voice control ---
        "voice_ready": "Voice control is ready.",
        "processing": "Processing.",
        "command_not_recognized": "Command not recognized.",
        "skip_using_default": "Skipping step. Using default value.",
        "tap_not_allowed_speak": "Please say the answer out loud, don't use the quick taps.",
        "understood_confirm": "I understood {text}. Is that right?",
        "skipping_validation": "Skipping validation.",
        "lets_repeat": "Alright, let's repeat it.",

        # Voice-recognized keywords (must be lowercase)
        "kw_capture": ["photo", "picture", "capture", "camera"],
        "kw_send": ["send", "upload", "board", "microbit"],
        "kw_explain": ["explain", "intelligence", "ai"],
        "kw_explain_phrase": "what does",
        "kw_read": ["read", "table", "qr"],
        "kw_tts": ["voice", "audio", "speak", "sound"],
        "kw_review": ["review", "modify", "variables"],
        "kw_yes": ["yes", "correct", "right"],
        "kw_skip": ["skip", "pass"],
        "kw_casual_yes": ["sure"],
        "list_join_and": ", and ",

        # --- translator.py: spoken errors and contexts during generation ---
        "err_expected_right": "# ERROR: The block '{block}' expected {expect} to its right.",
        "err_missing_after": "\n# ERROR: After '{block}', {expect} was missing.",
        "err_unknown_block": "# ERROR: The block '{block}' is unknown or not in the dictionary.",
        "err_loose_block": "# ERROR: The block '{block}' is loose.",
        "context_declare_var": "declare a new variable",
        "context_value_for": "the value for {name}",
        "context_general_order": "a general command",
        "context_control_method_subject": "a subject or sensor",
        "context_control_method_of": "the control method of {block}",
        "context_control_function_arg": "an argument or condition",
        "context_function_of": "the function {block}",
        "context_method_subject_needed": "a subject to apply it to",
        "context_subject_of": "the subject of {block}",
        "context_arg_number": "argument number {n}",
        "context_arg_of": "the argument of {block}",
        "context_condition_of": "the condition of {block}",
        "context_block_next_to": "the block next to {block}",
        "context_another_condition": "another condition",
        "context_arg_n_short": "argument {n}",
        "context_arg_of_short": "argument of {block}",

        # --- translator.py: spoken numbers ---
        "number_words": {
            "zero": "0", "one": "1", "two": "2", "three": "3", "four": "4",
            "five": "5", "six": "6", "seven": "7", "eight": "8", "nine": "9",
            "ten": "10", "eleven": "11", "twelve": "12", "thirteen": "13", "fourteen": "14",
            "fifteen": "15", "sixteen": "16", "seventeen": "17", "eighteen": "18",
            "nineteen": "19", "twenty": "20", "thirty": "30", "forty": "40",
            "fifty": "50", "sixty": "60", "seventy": "70", "eighty": "80",
            "ninety": "90", "hundred": "100",
        },
        "number_prefix": ["number "],
        "decimal_connectors": [" point "],
        "junction_word": " and ",
        "image_word": "image",
        # Musical notes for "play song": solfège and letter notation
        # indistinctly, always translated to the letter notation
        # MicroPython's music.play() expects.
        "note_names": {
            "do": "c", "re": "d", "mi": "e", "fa": "f", "sol": "g", "la": "a", "si": "b",
            "c": "c", "d": "d", "e": "e", "f": "f", "g": "g", "a": "a", "b": "b",
        },
    },
}


def t(key, **kwargs):
    """Devuelve el texto de 'key' en el idioma activo. Si lleva variables, se interpolan con .format()"""
    """Returns the text for 'key' in the active language. If it has variables, they're interpolated with .format()"""
    lang_dict = STRINGS.get(get_language(), STRINGS["es"])
    text = lang_dict.get(key)
    if text is None:
        text = STRINGS["es"].get(key, key)
    if kwargs and isinstance(text, str):
        return text.format(**kwargs)
    return text